### ISSUE TITLE
Is it possible to change the 'Completed' and 'Seeding' torrents font color?

### ISSUE THREAD

**Issue by KaXaSA** [jagannatharjun/qbt-theme#1]
So the theme is fantastic (darkstylesheet.qbtheme), my only issue is that both the 'Completed' and the 'Seeding/Stalled' (inactive) torrents font colors are too dark (Dark Blue and Black) making it kinda hard to read. Is there any way to change it?

Edit - This is how it looks in windows 10:

**darkstylesheet.qbtheme**
<img src="https://user-images.githubusercontent.com/6237603/70547002-f335a680-1b4e-11ea-8d07-69dadd1bdf82.png" width="300" height="310">
(GitHub made this one looks worse than the original image, the background color is not that dark and text is more readable -still not amazing-)

**amoled.qbtheme**
<img src="https://user-images.githubusercontent.com/6237603/70546999-f29d1000-1b4e-11ea-9f6c-e83d70b4218e.png" width="300" height="310">

**style.qbtheme**
<img src="https://user-images.githubusercontent.com/6237603/70547001-f29d1000-1b4e-11ea-9ba2-963d7a5b38a7.png" width="300" height="310">

**Comment by jagannatharjun** [comment]
well there is https://github.com/qbittorrent/qBittorrent/pull/11433,
I will work on it after some time

**Comment by aksae** [comment]
Is darkstylesheet.qbtheme supposed to look like this? The bright blue hurts eyes. rest is good.

![Screenshot (66)](https://user-images.githubusercontent.com/58544373/70208773-68226e00-1754-11ea-9868-f8ccca0a3e8f.png)

Also the AMOLED theme is bugged.

![Screenshot (67)](https://user-images.githubusercontent.com/58544373/70208954-e97a0080-1754-11ea-8834-0b20429f4ec6.png)

**Comment by ArtexJay** [comment]
Amoled looks the same as the above pics  and the style.qbtheme doesn't work for me at all.

**Comment by perplex51** [comment]
any news on the fix?

**Comment by gothicserpent** [comment]
would love to see the font colors be lighter as well. please try to update the stylesheet.

**Comment by sharkiller** [comment]
@jagannatharjun  4.2.2 released with the follow changes:  

`
- FEATURE: Allow transfer list text color changes through QSS (Prince Gupta)
- FEATURE: Refactored Transfer List code to allow theming. As a sideffect the row height has more padding. (glassez)
`

so this now can be fixed.

**Comment by jagannatharjun** [comment]
should be fixed now with https://github.com/jagannatharjun/qbt-theme/commit/3ed8d1b96edbc239c8e6eed4bb47194e770fc261

**Comment by gothicserpent** [comment]
![image](https://user-images.githubusercontent.com/36061843/77856289-ec3cad80-71aa-11ea-8c71-0eb92b5e7efe.png)

thanks a lot! @jagannatharjun  looks great!

**Comment by alik604** [comment]
I think the next change should be the _progress bar_, im using `darkstylesheet.qbtheme`. it's the only flaw. This might just be a qbittorrent side issue.

**Comment by Splike** [comment]
Using v1, when a torrent is selected, any torrent color is reverted back to the default white. Any color should be persistent, whether the torrent is selected or not.
