### ISSUE TITLE
Mumble Dark/Lite themes execution log visual bug

### ISSUE THREAD

**Issue by Lucane** [jagannatharjun/qbt-theme#11]
Execution log entries are clipping through other rows on the Mumble Dark and Lite themes. This bug does not occur on the Darkstylesheet theme.

![Annotation 2020-03-29 235536](https://user-images.githubusercontent.com/7999446/77860693-30669700-7219-11ea-80ea-6919148bf2ea.png)
![Annotation 2020-03-29 235536-2](https://user-images.githubusercontent.com/7999446/77860696-3197c400-7219-11ea-839b-c5cd2fd6b286.png)

**Comment by jagannatharjun** [comment]
![image](https://user-images.githubusercontent.com/34717789/77860886-4c753300-722f-11ea-9bf5-dcf7f5b13b8a.png)

This is an internal bug of qbittorrent

https://github.com/qbittorrent/qBittorrent/pull/12144 fixes it

**Comment by Lucane** [comment]
Gotcha! Fantastic work either way 👍

**Comment by maboroshin** [comment]
This could be solved. I think the solution was this.
QTabWidget QListView QLabel { /* patch : Excution Log */
  padding: 0px; /* change for : Excution Log's Line height */
}

**Comment by jagannatharjun** [comment]
> This could be solved. I think the solution was this.
> 
> ```
> QTabWidget QListView QLabel { /* patch : Excution Log */
>   padding: 0px; /* change for : Excution Log's Line height */
> }
> ```


lines are only half visible

**Comment by maboroshin** [comment]
Sorry, It seemed to be different issue. In last year's theme, +1 pixel reduce per line.

**Comment by jagannatharjun** [comment]
should be fixed

@maboroshin thanks for the idea

**Comment by jagannatharjun** [comment]
this can be termed as a partial fix since font-size doesn't match the rest of UI, Proper fix requires changes inside qbittorrent instead.
