### ISSUE TITLE
Color torrents when using Mumble-Dark.qbtheme

### ISSUE THREAD

**Issue by Splike** [jagannatharjun/qbt-theme#13]
Just like `Darkstylesheet.qbtheme`, where torrents that are "downloading" and "paused" get colored. I'd like to see this coloring also applied to Mumble-Dark.qbtheme.

I think the same green color used for the downloading line in the speed graph would be perfect for torrents with "downloading" status and maybe a red of the same brightness would fit nicely for paused torrents.

**Comment by jagannatharjun** [comment]
should be fixed in v1

**Comment by Splike** [comment]
Using v1, when a torrent is selected, any torrent color is reverted back to the default white. Any color should be persistent, whether the torrent is selected or not.
