### ISSUE TITLE
Unreadable Font Colors in mumble-dark

### ISSUE THREAD

**Issue by log1cb0mb** [jagannatharjun/qbt-theme#14]
Black and blue font color over dark background (Execution log and all hyperlinks)  why? :(

How about same white color as everywhere else in execution log while something more easily readable for hyperlinks?

**Comment by jagannatharjun** [comment]
requires
qbittorrent/qBittorrent#12144 
https://github.com/qbittorrent/qBittorrent/pull/12143

help me make maintainers interested ;)

**Comment by jagannatharjun** [comment]
fixed upstream
