### ISSUE TITLE
Potential virus in build tools

### ISSUE THREAD

**Issue by TeamDman** [jagannatharjun/qbt-theme#15]
[/Builds/Tools/rcc.exe](https://github.com/jagannatharjun/qbt-theme/tree/af8343367e7ee5ed60bd98dbbd1ecd670c7b9e59/Builds/tools) is being flagged as a virus by windows.
![image](https://user-images.githubusercontent.com/9356891/78511751-183ccd80-776d-11ea-8236-6df43cad8fba.png)
Thoughts?

**Comment by jagannatharjun** [comment]
False positive.
That is part of qt sdk, if don't wanna use this download qt sdk and you will find it inside bin folder, this is static build of my own so that we don't need dependences.

**Comment by TeamDman** [comment]
Thanks, just wanted to make sure!

**Comment by TeamDman** [comment]
Not quite sure what's going on, but it seems that multiple engines are flagging the file. Seems less likely as a false positive.
Is this file directly copied from the SDK, or can you share how to build the file?

https://www.virustotal.com/gui/file/a0af3a135d95baf2a66074e027cf450efa839824f41c8dc8ce41145228a496cb/detection
![image](https://user-images.githubusercontent.com/9356891/78526179-31fb0680-77a7-11ea-9b73-12cb5ceff2e7.png)

**Comment by jagannatharjun** [comment]
Download vcpkg
Then use
Vcpkg install qt5-base:x86-windows-static

**Comment by TeamDman** [comment]
I personally think that it would be inappropriate for myself to mark this as resolved since the file is still being flagged. I think a disclaimer in the README is the minimum I can propose for change here. I've PR'd a quick change, it's not legalese but it's more than nothing. If that gets merged then I'll close this myself.

**Comment by jagannatharjun** [comment]
replaced with the rcc from qt sdk, this may not work with windows 7, but whatever XD
