### ISSUE TITLE
Selected torrent background color in torrent search results same as unselected 

### ISSUE THREAD

**Issue by japanesephundroid** [jagannatharjun/qbt-theme#16]
This happens with the Mumble-Dark theme.

This is mostly OK when selecting only one torrent but when selecting multiple you can't tell which torrents are selected.

**Comment by kkwong7878** [comment]
Darkstylesheet.qbtheme 👍🤩👍
Thank you

**Comment by japanesephundroid** [comment]
Sorry for bumping but is there an update on this?

OS is Windows 10 latest stable by the way.

The above theme @kkwong7878 posted works OK by the way, what is your policy on this, is that one specifically for Windows 10?

**Comment by jagannatharjun** [comment]
use v2
