### ISSUE TITLE
[darkstylesheet] Can't distinguish unread and read entries in RSS tab

### ISSUE THREAD

**Issue by MikeZeDev** [jagannatharjun/qbt-theme#17]
Using last darkstylesheet and last qbt. Windows 10 (may not be relevant).

All text is white. I hope its not a QT or QBT limitation.

Thanks a lot.

**Comment by jagannatharjun** [comment]
needs changes in palette
https://github.com/qbittorrent/qBittorrent/pull/12143

**Comment by jagannatharjun** [comment]
use v2
