### ISSUE TITLE
mumble-dark.qbtheme on ubuntu

### ISSUE THREAD

**Issue by Spelvi** [jagannatharjun/qbt-theme#18]
Progress bar is not showing quite correct, look at screenshot, it is in ubuntu [19.10]

http://prntscr.com/rw8hq5

**Comment by franmartosr** [comment]
Same for me, I use Ubuntu 18.04. Also when progress bar is empty (0%) it's invisible.

**Comment by jagannatharjun** [comment]
fixed in upstream
