### ISSUE TITLE
"Use alternating row colors" not working or too dark to see any difference.

### ISSUE THREAD

**Issue by KaXaSA** [jagannatharjun/qbt-theme#19]
example: https://i.imgur.com/kY3B69Q.mp4

Tools > Options > Behavior
Under 'Transfer List'
'☑ Use alternating row colors'

btw: I love the mumble-dark theme 👍

**Comment by jagannatharjun** [comment]
please check the themes from master branch

**Comment by KaXaSA** [comment]
Thanks! :)

btw: I changed the alternate background color to 292929
to make it darker.

**Original**
<img src="https://user-images.githubusercontent.com/6237603/80898573-56310100-8cdb-11ea-83e5-05c67962a3da.png" width="300" height="310">

**Changed to 292929**
<img src="https://user-images.githubusercontent.com/6237603/80898581-6d6fee80-8cdb-11ea-8f11-bc75fffb49af.png" width="300" height="310">

```
QAbstractItemView {
  alternate-background-color: #292929; }
```

**Comment by stephen147** [comment]
> btw: I changed the alternate background color to 292929
> to make it darker.

Could this be the new default? Looks better.
