### ISSUE TITLE
material2.qbtheme for web-ui?

### ISSUE THREAD

**Issue by AlexR00T** [jagannatharjun/qbt-theme#2]
HI, I use nox version of qbittorrent as i have up and running like a tiny “qbt-server” and i really like how your material2 style looks. Material UI feels better and would love to see and implementation of this theme for web-ui. Further the line a proposition for qbittorrent would be to make a unified interface and so more simple styling for both.

**Comment by jagannatharjun** [comment]
I actually don't use Web-UI so I don't know how It actually works. So I can't help you with that.
