### ISSUE TITLE
URLs in comments are hard to read

### ISSUE THREAD

**Issue by stephen147** [jagannatharjun/qbt-theme#21]
It's hard to make out any URLs if in the General>Comments section with the shade of blue and the dark background.

**mumble-dark theme**

![image](https://user-images.githubusercontent.com/14054664/79621757-702fe880-810c-11ea-8046-faab7355a6d7.png)

**Comment by jagannatharjun** [comment]
Requires
https://github.com/qbittorrent/qBittorrent/pull/12143

**Comment by stephen147** [comment]
Thanks, what does that mean. The devs seem reluctant to add this to the current theme file if I'm not mistaken?

**Comment by jagannatharjun** [comment]
Yeap

**Comment by jagannatharjun** [comment]
fixed upstream

**Comment by stephen147** [comment]
This is good to know. Any ETA when this will be implemented?

**Comment by jagannatharjun** [comment]
> This is good to know. Any ETA when this will be implemented?

use qbittorrent v4.3
