### ISSUE TITLE
Center text in progress bar?

### ISSUE THREAD

**Issue by luckri13** [jagannatharjun/qbt-theme#22]
Centering the xx% text in the progress bar is already done for the contents of a torrent, but not the torrent itself.

![image](https://user-images.githubusercontent.com/15656046/85617376-6f14bd80-b65f-11ea-9d3f-8a3072b01b0d.png)

**Comment by jagannatharjun** [comment]
it's not windows?

**Comment by jagannatharjun** [comment]
fixed in qbittorrent upstream
