### ISSUE TITLE
[Mumble Dark] - Linked label is not colored

### ISSUE THREAD

**Issue by Symbai** [jagannatharjun/qbt-theme#27]
Linked labels in for example torrent comments are still dark blue which makes them unreadable in dark theme:

![image](https://user-images.githubusercontent.com/14368203/92227774-0d66a000-eea7-11ea-91f8-2b1b66637637.png)

**Comment by RabidWolf** [comment]
Completed torrents are also dark blue and are hard to read, could do making it lighter.

**Comment by jagannatharjun** [comment]
use v2
