### ISSUE TITLE
[breeze-dark] Torrent text is black on gray after upgrading qBittorent to 4.3.0

### ISSUE THREAD

**Issue by BrandonCardoso** [jagannatharjun/qbt-theme#28]
![image](https://user-images.githubusercontent.com/1226170/96389080-4cad2f80-117b-11eb-825a-a95757be701e.png)

**Comment by sjclayton** [comment]
Same issue on mumble-dark as well.

**Comment by Navneet-Suresh** [comment]
According to the latest release notes(qBittorrent v4.3.0 release).

> Theming support has been enhanced but previous theme bundles will not work properly with this release. Please contact the theme provider for a fix. The new format is described here.

**Comment by dexeonify** [comment]
qBittorrent v4.3.0 was just released. I guess it's just a matter of time when this will be fixed.
Apparently, the creator of this theme is also involved in the change.

> FEATURE: Many UI elements colors are themeable now (jagannatharjun)
> FEATURE: Allow changing GUI icons from theme bundles (jagannatharjun)

**Comment by kimpurcell** [comment]
hope this gets fixed soon.

**Comment by jagannatharjun** [comment]
use v2
