### ISSUE TITLE
Theme not loading

### ISSUE THREAD

**Issue by lssatvik** [jagannatharjun/qbt-theme#30]
I used your theme downloaded a long time back with qbittorrent v4.2.3. Today I updated to v4.3 and also downloaded your updated theme. But it does not load the theme anymore.

**Comment by jagannatharjun** [comment]
are you on Linux based system?

**Comment by lssatvik** [comment]
No, windows

**Comment by lssatvik** [comment]
I just restored the older version of your theme. It works, but the text is black on blue background in v4.3 making it difficult to see. The recent version does not work.

**Comment by jagannatharjun** [comment]
check if these works https://github.com/jagannatharjun/qbt-theme/files/5417781/new-icons.zip

**Comment by lssatvik** [comment]
All 3 of them work

**Comment by ashrafi91** [comment]
Hi.

I am on a Linux based system. The icons load after restarting qbittorrent, but the dark theme or any theme colors do not load. Is it a problem in Linux based systems?

**Comment by MrComexs** [comment]
The themes al don't work on qBittorrent v4.3.0.1 and I'm on windows 10 and have python 3.5 3.6 3.7 installed and have tryied the link you put 9 days ago in this thread.

**Comment by robinpaulson** [comment]
Yeah, I'm getting the same problem. qb 4.3.1 on Ubuntu 20.04, from the Launchpad ppa

**Comment by lssatvik** [comment]
Yes the themes stopped working again with qb 4.3.1 Windows 10 2004. Request you to diagnose the issue.

**Comment by lssatvik** [comment]
They are working, my bad, I downloaded the wrong file. Everyone download the zip file in the releases section on main page. The files there will work.
