### ISSUE TITLE
Buttons unresponsive unless text in the middle of the box is clicked

### ISSUE THREAD

**Issue by vekuda** [jagannatharjun/qbt-theme#31]
![qbittorrent_WqpKMdRo3s](https://user-images.githubusercontent.com/38732059/96848337-96846700-1454-11eb-80a8-8b29136bd225.png)
Issue experienced after applying _mumble-dark.qbtheme_ to qBittorrent v4.3.0.1 (x64)
OS: Windows 10 Pro 2004

**Description**
Apply _mumble-dark.qbtheme_ to qBittorrent 4.3.0+, restart the client and try to set a new Global Download Speed Limit using the Global Download Speed Limit icon in the bottom right corner of qBittorrent main window. 
If you click the 'OK' button without pointing at the word 'OK' inside the box, the button won't work. This doesn't happen if qBittorrent is running without a theme applied.

**Comment by hichemfantar** [comment]
Same, came here to report the same bug.
This is really annoying. First time this happened i thought my mouse was broken.

**Comment by ajcr07** [comment]
I'm having this problem too, specifically with mumble-dark, this affects all the buttons in the dialog boxes.

**Comment by Dillusional** [comment]
Same, the only theme affected least by this problem is darkstylesheet(but i hate that one). Please fix it so i can use my favourite mumble dark

**Comment by MrJones6** [comment]
I thought I was going insane. I have the same problem with the Breeze Dark theme.

**Comment by jagannatharjun** [comment]
qt bug https://bugreports.qt.io/browse/QTBUG-87845

know a workaround probably next weekend.

**Comment by hichemfantar** [comment]
So is this gonna be fixed soon?

**Comment by vekuda** [comment]
It was fixed in qt, so I guess it won't be long

https://bugreports.qt.io/browse/QTBUG-86587

**Comment by Hackerpcs** [comment]
4.3.1 fixes it

**Comment by vekuda** [comment]
qBittorrent v4.3.1 has solved the issue indeed
