### ISSUE TITLE
DPI issue with progress bar text [Win 10 20H2]

### ISSUE THREAD

**Issue by KrazyLurt** [jagannatharjun/qbt-theme#39]
While it is great that QB supports the progress bar to the themed , I have an issue with the %-text when using the application at >100% DPI scaling. 

For example at 200% Dpi the %-text in the progress bar is only shown  1/4 of the text. 

I don’t know if it because of QB not yet scaling everything but it isn’t an issue without a theme. 

This repository is great and I appreciate that there are instructions to build tweaks yourself, I have done adjustments to the text color and icons and rebuild a theme so if I could add some values to solve this, that would be awesome.

**Comment by jagannatharjun** [comment]
What os are you on?

**Comment by KrazyLurt** [comment]
I’m sorry, I forgot to mention that, I’m using Windows 10 v 20H2 build 19042.630

**Comment by jagannatharjun** [comment]
@KrazyLurt can you test this  https://drive.google.com/file/d/1A2ucrGE1hyAijJ5PIRMZRPZpsbgErpTE/view?usp=sharing
build from here https://github.com/jagannatharjun/qBittorrent/tree/fix-progress
