### ISSUE TITLE
Window title doesn't change color

### ISSUE THREAD

**Issue by cdalexndr** [jagannatharjun/qbt-theme#40]
I'm using breeze-dark theme, and whole window except the title are dark.
![qbittorrent_dark](https://user-images.githubusercontent.com/22418250/101796522-a98cec80-3b11-11eb-9218-6096fd86e785.png)
I'm also using windows dark theme, but no effect.

Isn't this supported?

**Comment by nero-0** [comment]
Title bar is controlled by windows, so you must change it manually.
![box](https://user-images.githubusercontent.com/42862510/101971458-2c946c80-3c10-11eb-8b5a-ffccf744eae3.png)
Did you check this option? this should work.

**Comment by nero-0** [comment]
Title bar is controlled by windows, so you must change it manually.
![box](https://user-images.githubusercontent.com/42862510/101971511-90b73080-3c10-11eb-969f-2c7fd12b8f78.png)
Did you check this option? should work.
