### ISSUE TITLE
🐞: Theme does not change

### ISSUE THREAD

**Issue by joe733** [jagannatharjun/qbt-theme#43]
Hi,

I've set the theme like this:

![](https://user-images.githubusercontent.com/38415384/103305784-0b19ea00-4a32-11eb-8216-f4d4579b11c4.png)

Only the `Preference` titlebar changes (even after restart). And the same goes for he following themes:

![](https://user-images.githubusercontent.com/38415384/103306013-8f6c6d00-4a32-11eb-8403-4d6023233031.png)

System : elementary OS 5.1.7
qBittorrent: v4.3.2

What can I do to debug?

**Comment by jagannatharjun** [comment]
https://github.com/qbittorrent/qBittorrent/issues/13410
