### ISSUE TITLE
Transfers hardly readable in most dark themes

### ISSUE THREAD

**Issue by amadeogarcia** [jagannatharjun/qbt-theme#45]
For some reason, the text is white everywhere except in the transfers window, so it is hard to read the information without selecting a particular transfer (in which case, the text turns white). Here are some screenshots:

### Mumble Dark Theme ###
![mumble-dark](https://user-images.githubusercontent.com/42990927/103354791-41d01e80-4a8b-11eb-89e6-f0794cfdad82.png "Mumble Dark Theme")

### Breeze Dark Theme ###
![breeze-dark](https://user-images.githubusercontent.com/42990927/103354934-a8edd300-4a8b-11eb-9334-4a0d9f4ba82a.png "Breeze Dark Theme")

**Comment by mattrossman** [comment]
Noticing this too after updating qBittorrent to v4.3.3. Not sure what version I had previously but text looked fine before.

**Comment by jagannatharjun** [comment]
update your theme
