### ISSUE TITLE
mumble dark theme is displaying half percentage signs

### ISSUE THREAD

**Issue by Lorenium** [jagannatharjun/qbt-theme#48]
This started happening after I updated to 4.3.2

![qbittorrent_ybbpd5WCKQ](https://user-images.githubusercontent.com/57680600/103529461-c90c0080-4e96-11eb-8e6f-5f88488d5d49.png)

**Comment by derei** [comment]
![qb_dark](https://user-images.githubusercontent.com/34483372/103588087-68091a80-4ee0-11eb-9d3a-841d8ce5593b.png)
I can confirm that all themes here have the progress value clipped. The font size should be decreased to display properly

**Comment by GGODestroyer** [comment]
have this not been fixed yet ?

**Comment by marciozomb13** [comment]
Confirmed.
![qbittorrent_2021-01-25_12-25-55](https://user-images.githubusercontent.com/2564929/105726242-9d65be80-5f08-11eb-95f7-e21226113442.png)

**Comment by wail-shudar** [comment]
Any chance of a quick fix for this?

**Comment by jagannatharjun** [comment]
was qbittorrent bug, fixed long ago

**Comment by GitExploraa** [comment]
still not fixed for the latest builds nope
