### ISSUE TITLE
amoled/grey theme bugged compared to the blue theme

### ISSUE THREAD

**Issue by OzakIOne** [jagannatharjun/qbt-theme#5]
![Untitled](https://user-images.githubusercontent.com/29860391/75067739-fe616700-54ed-11ea-981e-91b4e47e7869.png)

![image](https://user-images.githubusercontent.com/29860391/75067830-35377d00-54ee-11ea-8e89-78cef2cadaa3.png)

![image](https://user-images.githubusercontent.com/29860391/75067889-5304e200-54ee-11ea-91d5-751ca1a4ebe2.png)

**Comment by long-horse** [comment]
this is disgusting. i sincerely hope it broke in an update. who would release a tease of such abysmal quality?

**Comment by CrafterLaughter** [comment]
@jagannatharjun   Great effort.  I know theming can be challenging and such things are always a work in progress.  Perhaps it could help you if you tried to mirror the theme color schemes of this QBT fork?

https://github.com/suratovvlad/qbittorrent-installer/releases

**Comment by jagannatharjun** [comment]
amoled theme is removed.
