### ISSUE TITLE
Progress percent value clipped

### ISSUE THREAD

**Issue by FlaveC** [jagannatharjun/qbt-theme#50]
I have an increased font size set from the Windows "Ease of Access --> Make text bigger" setting. This has the unfortunate effect of clipping the bottom of the percent progress number. If I wanted to fix this, which element of your qbtheme file should I be looking at? Thanks for a great theme!

**Comment by jagannatharjun** [comment]
duplicate https://github.com/jagannatharjun/qbt-theme/issues/48
