### ISSUE TITLE
Recently your themes are not working

### ISSUE THREAD

**Issue by Mahdi-Noor-Hasan** [jagannatharjun/qbt-theme#53]
I installed your themes previously and it was working fine.  Recently I've downloaded it again and now it's not working. Themes from other sources are working fine.

**Comment by jagannatharjun** [comment]
not reproducible

**Comment by banderlog** [comment]
Tried with qbittorrent v4.3.9 on ubuntu 20.04 LTS -- not working

Log: `17.11.21 22:51 - Failed to load UI theme from file: "/home/user/Downloads/mumble-dark-nowshed.qbtheme"`

**Comment by o101010** [comment]
Hi @banderlog 
The themes are designed for windows. On Linux, it's more "qt version dependant".
I invite you to try my build on Linux, or creating yours based on the documentation in Builds/README.md.
https://github.com/o101010/qbt-theme-Linux

**Comment by banderlog** [comment]
@o101010 thanks!
