### ISSUE TITLE
Add a few screenshots

### ISSUE THREAD

**Issue by cotwitch** [jagannatharjun/qbt-theme#7]
If possible, it would be great to have a few screenshots showing off the various themes to help others coming here see what the themes look like before they make use of them.  Generally what I see in README's for other stylising repo's.

_Originally posted by @PompeiaPaetenari in https://github.com/jagannatharjun/qbt-theme/pull/6/commits/2d3f12d6430900345255aab4e381ac4d0df3c231_

**Comment by gothicserpent** [comment]
@cotwitch https://github.com/jagannatharjun/qbt-theme/issues/1 contains some screenshots so far. i think the dev @jagannatharjun is working on making the fonts lighter in the darkstylesheet.qbtheme hopefully.

**Comment by jagannatharjun** [comment]
fixed with https://github.com/jagannatharjun/qbt-theme/commit/3ed8d1b96edbc239c8e6eed4bb47194e770fc261
