### ISSUE TITLE
Mambo Dark theme white areas

### ISSUE THREAD

**Issue by Juggernaut1994** [jagannatharjun/qbt-theme#9]
Some of the areas are white (#f0f0f0) in Options, general, trackers, files tabs
I've checked qss file for this color, but couldn't find it
Win 10, qB 4.2.2

Some examples:
![image](https://user-images.githubusercontent.com/18756851/77848571-e0bfa580-71ef-11ea-9810-c5f871a48e06.png)
![image](https://user-images.githubusercontent.com/18756851/77848587-f9c85680-71ef-11ea-9382-a8138de6de60.png)
![image](https://user-images.githubusercontent.com/18756851/77848593-02209180-71f0-11ea-83e1-f5e8f0d4cd3a.png)

**Comment by stderr-to-devnull** [comment]
I confirm the issue, Win 10, qb 4.2.2. Otherwise a great theme.

**Comment by stephen147** [comment]
Confirmed.. was also about to post this issue.

**Comment by jagannatharjun** [comment]
should be fixed in https://github.com/jagannatharjun/qbt-theme/commit/423b48a3b319cb2b9e3a6a548c2e3440cfedf908
